-- Ohlins suspension components migration
-- Adds complete Ohlins fork and shock product lineup with ramp chamber support

-- Add ramp chamber pressure columns for both forks and shocks if they don't exist
ALTER TABLE public.suspension_setups 
ADD COLUMN IF NOT EXISTS shock_ramp_chamber_pressure INTEGER;

-- Delete existing Ohlins data to avoid duplicates (preserves other brands)
DELETE FROM public.suspension_components WHERE brand = 'Ohlins';

INSERT INTO public.suspension_components (component_type, brand, model, year, spring_type, damper_name, available_adjustments) VALUES

-- ========================================
-- OHLINS FORKS (With Ramp Chamber Support)
-- ========================================

-- Ohlins RXF36 (Enduro Fork) - TTX Air damper with RAMP CHAMBER
('fork', 'Ohlins', 'RXF36 M.2', 2026, 'air', 'TTX Air', 
'{
  "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": true,  
    "other_adjustments": []}'),
('fork', 'Ohlins', 'RXF36 M.2', 2025, 'air', 'TTX Air', 
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": true,  
    "other_adjustments": []}'),
('fork', 'Ohlins', 'RXF36 M.2', 2024, 'air', 'TTX Air', 
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": true,  
    "other_adjustments": []}'),
('fork', 'Ohlins', 'RXF36 M.2', 2023,  'air', 'TTX Air', 
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": true,  
    "other_adjustments": []}'),

-- Ohlins RXF38 (Enduro Fork) - TTX Air damper with RAMP CHAMBER
('fork', 'Ohlins', 'RXF38 M.2', 2026,  'air', 'TTX Air', 
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false,  
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": true,  
    "other_adjustments": []}'),
('fork', 'Ohlins', 'RXF38 M.2', 2025, 'air', 'TTX Air', 
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": true,  
    "other_adjustments": []}'),
('fork', 'Ohlins', 'RXF38 M.2', 2024, 'air', 'TTX Air', 
'{
   "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": true,  
    "other_adjustments": []}'),
('fork', 'Ohlins', 'RXF38 M.2', 2023, 'air', 'TTX Air', 
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false,  
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": true,  
    "other_adjustments": []}'),

-- Ohlins RXC34 (XC Fork) - With ramp chamber
('fork', 'Ohlins', 'RXC34 M.2', 2026, 'air', 'TTX Air', 
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": true,  
    "other_adjustments": []}'),
('fork', 'Ohlins', 'RXC34 M.2', 2025, 'air', 'TTX Air', 
'{
   "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false,  
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": true,  
    "other_adjustments": []}'),
('fork', 'Ohlins', 'RXC34 M.2', 2024, 'air', 'TTX Air', 
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": true,  
    "other_adjustments": []}'),

-- Ohlins DH38 (DH Fork) - TTX damper with RAMP CHAMBER
('fork', 'Ohlins', 'DH38 M.2', 2026, 'air', 'TTX', 
'{
   "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": true,  
    "other_adjustments": []}'),
('fork', 'Ohlins', 'DH38 M.2', 2025, 'air', 'TTX', 
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": true,  
    "other_adjustments": []}'),
('fork', 'Ohlins', 'DH38 M.2', 2024, 'air', 'TTX', 
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": true,  
    "other_adjustments": []}'),

-- ========================================
-- OHLINS SHOCKS
-- ========================================

-- Ohlins TTX2 Trail/Enduro Shock (Air)
('shock', 'Ohlins', 'TTX2 Air', 2026, 'air', 'TTX', 
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": false,  
    "other_adjustments": []}'),
('shock', 'Ohlins', 'TTX2 Air', 2025, 'air', 'TTX', 
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": false,  
    "other_adjustments": []}'),
('shock', 'Ohlins', 'TTX2 Air', 2024, 'air', 'TTX', 
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": false,  
    "other_adjustments": []}'),
('shock', 'Ohlins', 'TTX2 Air', 2023, 'air', 'TTX', 
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": false,  
    "other_adjustments": []}'),
('shock', 'Ohlins', 'TTX1 Air', 2022, 'air', 'TTX',
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": false,  
    "other_adjustments": []}'),

-- Ohlins TTX Coil (DH/Enduro)
('shock', 'Ohlins', 'TTX Coil', 2026, 'coil', 'TTX',
 '{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false,
    "air_pressure": false, 
    "volume_spacers": false, 
    "spring_rate": true, 
    "has_ramp_chamber": true,  
    "other_adjustments": []}'),
('shock', 'Ohlins', 'TTX Coil', 2025, 'coil', 'TTX', 
'{
     "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": false, 
    "volume_spacers": false, 
    "spring_rate": true, 
    "has_ramp_chamber": true,  
    "other_adjustments": []}'),
('shock', 'Ohlins', 'TTX Coil', 2024, 'coil', 'TTX', 
'{
     "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false,
    "air_pressure": false, 
    "volume_spacers": false, 
    "spring_rate": true, 
    "has_ramp_chamber": false,  
    "other_adjustments": []}'),

-- Ohlins TXC2 XC Shock
('shock', 'Ohlins', 'TXC2 Air', 2026, 'air', 'TTX', 
'{
     "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false,
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": false,  
    "other_adjustments": []}'),
('shock', 'Ohlins', 'TXC2 Air', 2025, 'air', 'TTX', 
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": false,  
    "other_adjustments": []}'),
('shock', 'Ohlins', 'TXC2 Air', 2024, 'air', 'TTX', 
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": false,  
    "other_adjustments": []}'),
('shock', 'Ohlins', 'TXC2 Air', 2023, 'air', 'TTX', 
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": false,  
    "other_adjustments": []}'),
('shock', 'Ohlins', 'TXC1 Air', 2022, 'air', 'TTX',
'{
    "compression": false,
    "hsc": true, 
    "lsc": true, 
    "rebound": true, 
    "hsr": false, 
    "lsr": false, 
    "air_pressure": true, 
    "volume_spacers": true, 
    "spring_rate": false, 
    "has_ramp_chamber": false,  
    "other_adjustments": []}');

COMMIT;
