-- Comprehensive suspension components database
-- Combines all brands: Fox, RockShox, Cane Creek, and Ohlins
-- Includes accurate damper adjustments for each model and year (2021-2026)

-- Clear existing data first
TRUNCATE TABLE public.suspension_components;

-- ========================================
-- FOX FORKS
-- ========================================

INSERT INTO public.suspension_components (component_type, brand, model, year, spring_type, damper_name, available_adjustments) VALUES

-- Fox 32 (XC Fork) - Grip SL, GRIP dampers
('fork', 'Fox', '32 SC Factory', 2026, 'air', 'GRIP SL', '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),
('fork', 'Fox', '32 SC Performance', 2026, 'air', 'GRIP', '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),
('fork', 'Fox', '32 SC Factory', 2025, 'air', 'GRIP SL', '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),
('fork', 'Fox', '32 SC Performance', 2025, 'air', 'GRIP', '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),
('fork', 'Fox', '32 SC Factory', 2024, 'air', 'FIT4', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '32 SC Performance Elite', 2024, 'air', 'FIT4', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '32 Performance', 2024, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),
('fork', 'Fox', '32 Factory', 2023, 'air', 'FIT4', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '32 Performance Elite', 2023, 'air', 'FIT4', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '32 Performance', 2023, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),

-- Fox 34 (Trail Fork) - GRIP X2, GRIP, FIT dampers
('fork', 'Fox', '34 Factory', 2026, 'air', 'GRIP X2', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '34 Performance Elite', 2026, 'air', 'GRIP', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '34 Performance', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),
('fork', 'Fox', '34 Factory', 2025, 'air', 'GRIP X2', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '34 Performance Elite', 2025, 'air', 'GRIP', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '34 Performance', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),
('fork', 'Fox', '34 Factory', 2024, 'air', 'GRIP X2', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '34 Performance Elite', 2024, 'air', 'GRIP', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '34 Performance', 2024, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),
('fork', 'Fox', '34 Factory', 2023, 'air', 'GRIP X2', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '34 Performance Elite', 2023, 'air', 'GRIP', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '34 Performance', 2023, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),

-- Fox 36 (Enduro Fork) - GRIP X2, GRIP dampers
('fork', 'Fox', '36 Factory', 2026, 'air', 'GRIP X2', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '36 Performance Elite', 2026, 'air', 'GRIP', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '36 Performance', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),
('fork', 'Fox', '36 Factory', 2025, 'air', 'GRIP X2', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '36 Performance Elite', 2025, 'air', 'GRIP', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '36 Performance', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),
('fork', 'Fox', '36 Factory', 2024, 'air', 'GRIP X2', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '36 Performance Elite', 2024, 'air', 'GRIP', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '36 Performance', 2024, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),
('fork', 'Fox', '36 Factory', 2023, 'air', 'GRIP X2', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '36 Performance Elite', 2023, 'air', 'GRIP', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '36 Performance', 2023, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),

-- Fox 38 (Enduro/DH Fork) - GRIP X2 damper
('fork', 'Fox', '38 Factory', 2026, 'air', 'GRIP X2', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '38 Performance Elite', 2026, 'air', 'GRIP', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '38 Factory', 2025, 'air', 'GRIP X2', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '38 Performance Elite', 2025, 'air', 'GRIP', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '38 Factory', 2024, 'air', 'GRIP X2', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '38 Performance Elite', 2024, 'air', 'GRIP', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '38 Factory', 2023, 'air', 'GRIP X2', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '38 Performance Elite', 2023, 'air', 'GRIP', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- Fox 40 (DH Fork) - GRIP X2 damper
('fork', 'Fox', '40 Factory', 2026, 'air', 'GRIP X2', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '40 Factory', 2025, 'air', 'GRIP X2', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '40 Factory', 2024, 'air', 'GRIP X2', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Fox', '40 Factory', 2023, 'air', 'GRIP X2', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- ========================================
-- FOX SHOCKS
-- ========================================

-- Fox Float X2 (Enduro/DH Shock)
('shock', 'Fox', 'Float X2 Factory', 2026, 'air', null, '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Fox', 'Float X2 Factory', 2025, 'air', null, '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Fox', 'Float X2 Factory', 2024, 'air', null, '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Fox', 'Float X2 Factory', 2023, 'air', null, '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- Fox Float X (Trail Shock)
('shock', 'Fox', 'Float X Factory', 2026, 'air', null, '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Fox', 'Float X Performance Elite', 2026, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Fox', 'Float X Performance', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),
('shock', 'Fox', 'Float X Factory', 2025, 'air', null, '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Fox', 'Float X Performance Elite', 2025, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Fox', 'Float X Performance', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),
('shock', 'Fox', 'Float X Factory', 2024, 'air', null, '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Fox', 'Float X Performance Elite', 2024, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Fox', 'Float X Performance', 2024, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),

-- Fox DHX2 (DH Coil Shock)
('shock', 'Fox', 'DHX2 Factory', 2026, 'coil', null, '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Fox', 'DHX2 Factory', 2025, 'coil', null, '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Fox', 'DHX2 Factory', 2024, 'coil', null, '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- ========================================
-- ROCKSHOX FORKS
-- ========================================

-- BoXXer (DH Fork) - Charger 3.1 damper
('fork', 'RockShox', 'BoXXer Ultimate', 2026, 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'BoXXer Base', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'BoXXer Ultimate', 2025, 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'BoXXer Base', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'BoXXer Ultimate', 2024, 'air', 'Charger 3.0', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'BoXXer Base', 2024, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'BoXXer Ultimate', 2023, 'air', 'Charger 3.0', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'BoXXer Ultimate', 2022, 'air', 'Charger 2.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'BoXXer Ultimate', 2021, 'air', 'Charger 2.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- Lyrik - Charger 3.1/2.1 damper
('fork', 'RockShox', 'Lyrik Ultimate', 2026, 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Select+', 2026, 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Select', 2026, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Base', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Ultimate', 2025, 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Select+', 2025, 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Select', 2025, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Base', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Ultimate', 2024, 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Select+', 2024, 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Select', 2024, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Base', 2024, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Ultimate', 2023, 'air', 'Charger 3', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Select+', 2023, 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Ultimate', 2022, 'air', 'Charger 2.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Ultimate', 2021, 'air', 'Charger 2.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- Pike - Charger 3.1/2.1 damper
('fork', 'RockShox', 'Pike Ultimate', 2026, 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Select+', 2026, 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Select', 2026, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Base', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike DJ', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Ultimate', 2025, 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Select+', 2025, 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Select', 2025, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Base', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike DJ', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Ultimate', 2024, 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Select+', 2024, 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Select', 2024, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Base', 2024, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike DJ', 2024, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Ultimate', 2023, 'air', 'Charger 3', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Select+', 2023, 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Ultimate', 2022, 'air', 'Charger 2.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Ultimate', 2021, 'air', 'Charger 2.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- Zeb (Enduro Fork) - Charger 3.1/2.1
('fork', 'RockShox', 'Zeb Ultimate', 2026, 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Select+', 2026, 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Select', 2026, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Ultimate', 2025, 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Select+', 2025, 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Select', 2025, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Ultimate', 2024, 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Select+', 2024, 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Select', 2024, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Ultimate', 2023, 'air', 'Charger 3', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Ultimate', 2022, 'air', 'Charger 2.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Ultimate', 2021, 'air', 'Charger 2.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- Sid (XC Fork) - TwistLoc damper
('fork', 'RockShox', 'Sid Ultimate 3P', 2026, 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Ultimate 2P', 2026, 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid Select+ 3P', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Select+ 2P', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid Select 3P', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Select 2P', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid Ultimate 3P', 2025, 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Ultimate 2P', 2025, 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid Select+ 3P', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Select+ 2P', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid Select 3P', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Select 2P', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid Ultimate 3P', 2024, 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Ultimate 2P', 2024, 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid Select+ 3P', 2024, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Select+ 2P', 2024, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid Select 3P', 2024, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Select 2P', 2024, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid Ultimate 3P', 2023, 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Ultimate 2P', 2023, 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),

-- Sid SL (Super Light XC Fork) - Brain/TwistLoc
('fork', 'RockShox', 'Sid SL Ultimate Brain', 2026, 'air', 'Brain', '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["Brain Auto-Compression"]}'),
('fork', 'RockShox', 'Sid SL Ultimate 3P', 2026, 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid SL Ultimate 2P', 2026, 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid SL Select+ 3P', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid SL Select+ 2P', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid SL Select 3P', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid SL Select 2P', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid SL Ultimate Brain', 2025, 'air', 'Brain', '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["Brain Auto-Compression"]}'),
('fork', 'RockShox', 'Sid SL Ultimate 3P', 2025, 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid SL Ultimate 2P', 2025, 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid SL Select+ 3P', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid SL Select+ 2P', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid SL Select 3P', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid SL Select 2P', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid SL Ultimate Brain', 2024, 'air', 'Brain', '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["Brain Auto-Compression"]}'),
('fork', 'RockShox', 'Sid SL Ultimate 3P', 2024, 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid SL Ultimate 2P', 2024, 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),

-- ========================================
-- ROCKSHOX SHOCKS
-- ========================================

-- RockShox Super Deluxe
('shock', 'RockShox', 'Super Deluxe Ultimate', 2026, 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["HBO"]}'),
('shock', 'RockShox', 'Super Deluxe Select+', 2026, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Super Deluxe Select', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Super Deluxe Ultimate', 2025, 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["HBO"]}'),
('shock', 'RockShox', 'Super Deluxe Select+', 2025, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Super Deluxe Select', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Super Deluxe Ultimate', 2024, 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["HBO"]}'),
('shock', 'RockShox', 'Super Deluxe Select+', 2024, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Super Deluxe Select', 2024, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Super Deluxe Ultimate', 2023, 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- RockShox Super Deluxe Coil
('shock', 'RockShox', 'Super Deluxe Ultimate Coil', 2026, 'coil', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["HBO"]}'),
('shock', 'RockShox', 'Super Deluxe Select+ Coil', 2026, 'coil', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Super Deluxe Ultimate Coil', 2025, 'coil', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["HBO"]}'),
('shock', 'RockShox', 'Super Deluxe Select+ Coil', 2025, 'coil', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Super Deluxe Ultimate Coil', 2024, 'coil', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["HBO"]}'),
('shock', 'RockShox', 'Super Deluxe Select+ Coil', 2024, 'coil', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- RockShox Deluxe
('shock', 'RockShox', 'Deluxe Ultimate', 2026, 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Deluxe Select+', 2026, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Deluxe Select', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Deluxe Ultimate', 2025, 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Deluxe Select+', 2025, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Deluxe Select', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Deluxe Ultimate', 2024, 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Deluxe Select+', 2024, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Deluxe Select', 2024, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- RockShox SidLuxe (XC Shock)
('shock', 'RockShox', 'SidLuxe Ultimate', 2026, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('shock', 'RockShox', 'SidLuxe Select+', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('shock', 'RockShox', 'SidLuxe Ultimate', 2025, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('shock', 'RockShox', 'SidLuxe Select+', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('shock', 'RockShox', 'SidLuxe Ultimate', 2024, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('shock', 'RockShox', 'SidLuxe Select+', 2024, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),

-- RockShox Vivid (DH Shock)
('shock', 'RockShox', 'Vivid Ultimate', 2026, 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Vivid Ultimate Coil', 2026, 'coil', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Vivid Ultimate', 2025, 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Vivid Ultimate Coil', 2025, 'coil', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Vivid Ultimate', 2024, 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Vivid Ultimate Coil', 2024, 'coil', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- ========================================
-- CANE CREEK FORKS
-- ========================================

-- Cane Creek Helm (Enduro Fork) - DBair damper
('fork', 'Cane Creek', 'Helm MKII Air', 2026, 'air', 'DBair', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Cane Creek', 'Helm MKII Coil', 2026, 'coil', 'DBcoil', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Cane Creek', 'Helm MKII Air', 2025, 'air', 'DBair', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Cane Creek', 'Helm MKII Coil', 2025, 'coil', 'DBcoil', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Cane Creek', 'Helm MKII Air', 2024, 'air', 'DBair', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Cane Creek', 'Helm MKII Coil', 2024, 'coil', 'DBcoil', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- ========================================
-- CANE CREEK SHOCKS
-- ========================================

-- Cane Creek DB Air IL (Inline)
('shock', 'Cane Creek', 'DB Air IL', 2026, 'air', 'DBair IL', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Cane Creek', 'DB Air IL', 2025, 'air', 'DBair IL', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Cane Creek', 'DB Air IL', 2024, 'air', 'DBair IL', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- Cane Creek DB Coil IL (Inline Coil)
('shock', 'Cane Creek', 'DB Coil IL', 2026, 'coil', 'DBcoil IL', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Cane Creek', 'DB Coil IL', 2025, 'coil', 'DBcoil IL', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Cane Creek', 'DB Coil IL', 2024, 'coil', 'DBcoil IL', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- Cane Creek Kitsuma Air
('shock', 'Cane Creek', 'Kitsuma Air', 2026, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Cane Creek', 'Kitsuma Air', 2025, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Cane Creek', 'Kitsuma Air', 2024, 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- Cane Creek Tigon
('shock', 'Cane Creek', 'Tigon Air', 2026, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),
('shock', 'Cane Creek', 'Tigon Air', 2025, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),
('shock', 'Cane Creek', 'Tigon Air', 2024, 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": true, "other_adjustments": []}'),

-- ========================================
-- OHLINS FORKS (With Ramp Chamber Support)
-- ========================================

-- Ohlins RXF36 (Enduro Fork) - TTX Air damper with RAMP CHAMBER
('fork', 'Ohlins', 'RXF36 M.2', 2026, 'air', 'TTX Air', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": true, "compression": false, "other_adjustments": []}'),
('fork', 'Ohlins', 'RXF36 M.2', 2025, 'air', 'TTX Air', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": true, "compression": false, "other_adjustments": []}'),
('fork', 'Ohlins', 'RXF36 M.2', 2024, 'air', 'TTX Air', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": true, "compression": false, "other_adjustments": []}'),
('fork', 'Ohlins', 'RXF36 M.2', 2023, 'air', 'TTX Air', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": true, "compression": false, "other_adjustments": []}'),

-- Ohlins RXF38 (Enduro Fork) - TTX Air damper with RAMP CHAMBER
('fork', 'Ohlins', 'RXF38 M.2', 2026, 'air', 'TTX Air', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": true, "compression": false, "other_adjustments": []}'),
('fork', 'Ohlins', 'RXF38 M.2', 2025, 'air', 'TTX Air', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": true, "compression": false, "other_adjustments": []}'),
('fork', 'Ohlins', 'RXF38 M.2', 2024, 'air', 'TTX Air', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": true, "compression": false, "other_adjustments": []}'),
('fork', 'Ohlins', 'RXF38 M.2', 2023, 'air', 'TTX Air', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": true, "compression": false, "other_adjustments": []}'),

-- Ohlins RXC34 (XC Fork) - No ramp chamber
('fork', 'Ohlins', 'RXC34 M.2', 2026, 'air', 'TTX Air', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Ohlins', 'RXC34 M.2', 2025, 'air', 'TTX Air', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'Ohlins', 'RXC34 M.2', 2024, 'air', 'TTX Air', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- Ohlins DH38 (DH Fork) - TTX damper with RAMP CHAMBER
('fork', 'Ohlins', 'DH38 M.2', 2026, 'air', 'TTX', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": true, "compression": false, "other_adjustments": []}'),
('fork', 'Ohlins', 'DH38 M.2', 2025, 'air', 'TTX', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": true, "compression": false, "other_adjustments": []}'),
('fork', 'Ohlins', 'DH38 M.2', 2024, 'air', 'TTX', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": false, "has_ramp_chamber": true, "compression": false, "other_adjustments": []}'),

-- ========================================
-- OHLINS SHOCKS
-- ========================================

-- Ohlins TTX Air (Trail/Enduro)
('shock', 'Ohlins', 'TTX Air', 2026, 'air', 'TTX Air', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Ohlins', 'TTX Air', 2025, 'air', 'TTX Air', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Ohlins', 'TTX Air', 2024, 'air', 'TTX Air', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- Ohlins TTX Coil (DH/Enduro)
('shock', 'Ohlins', 'TTX Coil', 2026, 'coil', 'TTX', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Ohlins', 'TTX Coil', 2025, 'coil', 'TTX', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Ohlins', 'TTX Coil', 2024, 'coil', 'TTX', '{"hsc": true, "lsc": true, "hsr": true, "lsr": true, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": false, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- Ohlins TXC XC Shock
('shock', 'Ohlins', 'TXC Air', 2026, 'air', 'TXC', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Ohlins', 'TXC Air', 2025, 'air', 'TXC', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'Ohlins', 'TXC Air', 2024, 'air', 'TXC', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}');
