-- Add ramp chamber support for forks (second air chamber)
-- This migration adds columns for tracking ramp chamber pressure and updates component data

-- Add ramp chamber columns to suspension_setups table
ALTER TABLE public.suspension_setups 
ADD COLUMN IF NOT EXISTS fork_ramp_chamber_pressure DECIMAL(5,1); -- PSI for ramp chamber

-- Add ramp chamber tracking to suspension_components available_adjustments
-- We'll update the JSONB column to include has_ramp_chamber boolean

-- Update component data with ramp chamber support
-- Clear existing data first (optional - comment out if you want to keep existing data)
TRUNCATE TABLE public.suspension_components;


-- ========================================
-- ROCKSHOX FORKS
-- ========================================

-- BoXXer (DH Fork) - Charger 3.1 damper
INSERT INTO public.suspension_components (component_type, brand, model, year, damper_variant, spring_type, damper_name, available_adjustments) VALUES
('fork', 'RockShox', 'BoXXer Ultimate', 2026, 'Ultimate', 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'BoXXer Base', 2026, 'Base', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'BoXXer Ultimate', 2025, 'Ultimate', 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'BoXXer Base', 2025, 'Base', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'BoXXer Ultimate', 2024, 'Ultimate', 'air', 'Charger 3.0', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'BoXXer Base', 2024, 'Base', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'BoXXer Ultimate', 2023, 'Ultimate', 'air', 'Charger 3.0', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'BoXXer Ultimate', 2022, 'Ultimate', 'air', 'Charger 2.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'BoXXer Ultimate', 2021, 'Ultimate', 'air', 'Charger 2.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- Lyrik - Charger 3.1/2.1 damper
('fork', 'RockShox', 'Lyrik Ultimate', 2026, 'Ultimate', 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Select+', 2026, 'Select+', 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Select', 2026, 'Select', 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Base', 2026, 'Base', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Ultimate', 2025, 'Ultimate', 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Select+', 2025, 'Select+', 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Select', 2025, 'Select', 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Base', 2025, 'Base', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Ultimate', 2024, 'Ultimate', 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Select+', 2024, 'Select+', 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Select', 2024, 'Select', 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Base', 2024, 'Base', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Ultimate', 2023, 'Ultimate', 'air', 'Charger 3', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Select+', 2023, 'Select+', 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Ultimate', 2022, 'Ultimate', 'air', 'Charger 2.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Lyrik Ultimate', 2021, 'Ultimate', 'air', 'Charger 2.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- Pike - Charger 3.1/2.1 damper
('fork', 'RockShox', 'Pike Ultimate', 2026, 'Ultimate', 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Select+', 2026, 'Select+', 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Select', 2026, 'Select', 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Base', 2026, 'Base', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike DJ', 2026, 'DJ', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Ultimate', 2025, 'Ultimate', 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Select+', 2025, 'Select+', 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Select', 2025, 'Select', 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Base', 2025, 'Base', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike DJ', 2025, 'DJ', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Ultimate', 2024, 'Ultimate', 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Select+', 2024, 'Select+', 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Select', 2024, 'Select', 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Base', 2024, 'Base', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike DJ', 2024, 'DJ', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": false, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Ultimate', 2023, 'Ultimate', 'air', 'Charger 3', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Select+', 2023, 'Select+', 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Ultimate', 2022, 'Ultimate', 'air', 'Charger 2.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Pike Ultimate', 2021, 'Ultimate', 'air', 'Charger 2.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- Zeb (Enduro Fork) - Charger 3.1/2.1
('fork', 'RockShox', 'Zeb Ultimate', 2026, 'Ultimate', 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Select+', 2026, 'Select+', 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Select', 2026, 'Select', 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Ultimate', 2025, 'Ultimate', 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Select+', 2025, 'Select+', 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Select', 2025, 'Select', 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Ultimate', 2024, 'Ultimate', 'air', 'Charger 3.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Select+', 2024, 'Select+', 'air', 'Charger', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Select', 2024, 'Select', 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Ultimate', 2023, 'Ultimate', 'air', 'Charger 3', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Ultimate', 2022, 'Ultimate', 'air', 'Charger 2.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('fork', 'RockShox', 'Zeb Ultimate', 2021, 'Ultimate', 'air', 'Charger 2.1', '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- Sid (XC Fork) - TwistLoc damper
('fork', 'RockShox', 'Sid Ultimate 3P', 2026, 'Ultimate', 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Ultimate 2P', 2026, 'Ultimate', 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid Select+ 3P', 2026, 'Select+', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Select+ 2P', 2026, 'Select+', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid Select 3P', 2026, 'Select', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Select 2P', 2026, 'Select', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid Ultimate 3P', 2025, 'Ultimate', 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Ultimate 2P', 2025, 'Ultimate', 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid Select+ 3P', 2025, 'Select+', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Select+ 2P', 2025, 'Select+', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid Select 3P', 2025, 'Select', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Select 2P', 2025, 'Select', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid Ultimate 3P', 2024, 'Ultimate', 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Ultimate 2P', 2024, 'Ultimate', 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid Select+ 3P', 2024, 'Select+', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Select+ 2P', 2024, 'Select+', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid Select 3P', 2024, 'Select', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Select 2P', 2024, 'Select', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid Ultimate 3P', 2023, 'Ultimate', 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid Ultimate 2P', 2023, 'Ultimate', 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),

-- Sid SL (Super Light XC Fork) - Brain/TwistLoc
('fork', 'RockShox', 'Sid SL Ultimate Brain', 2026, 'Ultimate', 'air', 'Brain', '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["Brain Auto-Compression"]}'),
('fork', 'RockShox', 'Sid SL Ultimate 3P', 2026, 'Ultimate', 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid SL Ultimate 2P', 2026, 'Ultimate', 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid SL Select+ 3P', 2026, 'Select+', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid SL Select+ 2P', 2026, 'Select+', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid SL Select 3P', 2026, 'Select', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid SL Select 2P', 2026, 'Select', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid SL Ultimate Brain', 2025, 'Ultimate', 'air', 'Brain', '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["Brain Auto-Compression"]}'),
('fork', 'RockShox', 'Sid SL Ultimate 3P', 2025, 'Ultimate', 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid SL Ultimate 2P', 2025, 'Ultimate', 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid SL Select+ 3P', 2025, 'Select+', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid SL Select+ 2P', 2025, 'Select+', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid SL Select 3P', 2025, 'Select', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid SL Select 2P', 2025, 'Select', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('fork', 'RockShox', 'Sid SL Ultimate Brain', 2024, 'Ultimate', 'air', 'Brain', '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["Brain Auto-Compression"]}'),
('fork', 'RockShox', 'Sid SL Ultimate 3P', 2024, 'Ultimate', 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('fork', 'RockShox', 'Sid SL Ultimate 2P', 2024, 'Ultimate', 'air', 'TwistLoc', '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),

-- ========================================
-- ROCKSHOX SHOCKS
-- ========================================

-- RockShox Super Deluxe
('shock', 'RockShox', 'Super Deluxe Ultimate', 2026, 'Ultimate', 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["HBO"]}'),
('shock', 'RockShox', 'Super Deluxe Select+', 2026, 'Select+', 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Super Deluxe Select', 2026, 'Select', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Super Deluxe Ultimate', 2025, 'Ultimate', 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["HBO"]}'),
('shock', 'RockShox', 'Super Deluxe Select+', 2025, 'Select+', 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Super Deluxe Select', 2025, 'Select', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Super Deluxe Ultimate', 2024, 'Ultimate', 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["HBO"]}'),
('shock', 'RockShox', 'Super Deluxe Select+', 2024, 'Select+', 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Super Deluxe Select', 2024, 'Select', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Super Deluxe Ultimate', 2023, 'Ultimate', 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- RockShox Super Deluxe Coil
('shock', 'RockShox', 'Super Deluxe Ultimate Coil', 2026, 'Ultimate', 'coil', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["HBO"]}'),
('shock', 'RockShox', 'Super Deluxe Select+ Coil', 2026, 'Select+', 'coil', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Super Deluxe Ultimate Coil', 2025, 'Ultimate', 'coil', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["HBO"]}'),
('shock', 'RockShox', 'Super Deluxe Select+ Coil', 2025, 'Select+', 'coil', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Super Deluxe Ultimate Coil', 2024, 'Ultimate', 'coil', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["HBO"]}'),
('shock', 'RockShox', 'Super Deluxe Select+ Coil', 2024, 'Select+', 'coil', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- RockShox Deluxe
('shock', 'RockShox', 'Deluxe Ultimate', 2026, 'Ultimate', 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Deluxe Select+', 2026, 'Select+', 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Deluxe Select', 2026, 'Select', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Deluxe Ultimate', 2025, 'Ultimate', 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Deluxe Select+', 2025, 'Select+', 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Deluxe Select', 2025, 'Select', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Deluxe Ultimate', 2024, 'Ultimate', 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Deluxe Select+', 2024, 'Select+', 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Deluxe Select', 2024, 'Select', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),

-- RockShox SidLuxe (XC Shock)
('shock', 'RockShox', 'SidLuxe Ultimate', 2026, 'Ultimate', 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('shock', 'RockShox', 'SidLuxe Select+', 2026, 'Select+', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('shock', 'RockShox', 'SidLuxe Ultimate', 2025, 'Ultimate', 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('shock', 'RockShox', 'SidLuxe Select+', 2025, 'Select+', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),
('shock', 'RockShox', 'SidLuxe Ultimate', 2024, 'Ultimate', 'air', null, '{"hsc": false, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["3-position compression"]}'),
('shock', 'RockShox', 'SidLuxe Select+', 2024, 'Select+', 'air', null, '{"hsc": false, "lsc": false, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": ["2-position compression"]}'),

-- RockShox Vivid (DH Shock)
('shock', 'RockShox', 'Vivid Ultimate', 2026, 'Ultimate', 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Vivid Ultimate Coil', 2026, 'Ultimate', 'coil', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Vivid Ultimate', 2025, 'Ultimate', 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Vivid Ultimate Coil', 2025, 'Ultimate', 'coil', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Vivid Ultimate', 2024, 'Ultimate', 'air', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": true, "volume_spacers": true, "spring_rate": false, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
('shock', 'RockShox', 'Vivid Ultimate Coil', 2024, 'Ultimate', 'coil', null, '{"hsc": true, "lsc": true, "hsr": false, "lsr": false, "air_pressure": false, "volume_spacers": false, "spring_rate": true, "rebound": true, "has_ramp_chamber": false, "compression": false, "other_adjustments": []}'),
